blueprint:
  name: Alexa Blind Reverse (Matter Fix) - input_number to cover
  description: Reverse blind direction for Alexa via Matter bridge using an input_number as the Alexa-facing control.
  domain: automation
  input:
    alexa_slider:
      name: Alexa virtual blind (input_number)
      selector:
        entity:
          domain: input_number
    real_blind:
      name: Real blind entity
      selector:
        entity:
          domain: cover

mode: restart

trigger:
  - platform: state
    entity_id: !input alexa_slider

condition: []

action:
  - service: cover.set_cover_position
    target:
      entity_id: !input real_blind
    data:
      position: "{{ 100 - (trigger.to_state.state | int(0)) }}"
