blueprint:
  name: IKEA Styrbar - Multi target + custom Left/Right (NO errors)
  description: >
    Control multiple light/switch targets with IKEA STYRBAR via Zigbee2MQTT.
    ON/OFF + dim up/down control the selected target.
    Left/Right click run custom actions you define (no cycling, no holds, no blink).
  domain: automation

  input:
    switch_remote:
      name: Styrbar switch remote
      selector:
        device:
          integration: mqtt
          manufacturer: IKEA
          model: STYRBAR remote control
          multiple: false

    targets:
      name: Light/Switch targets
      selector:
        entity:
          multiple: true
          reorder: false
          filter:
            - domain:
                - light
                - switch

    selected_target:
      name: Selected target index (Input Number)
      description: >
        Input number stores the index (0 = first item in targets list).
        Since cycling is removed, keep this helper at 0 unless you change it elsewhere.
      selector:
        entity:
          multiple: false
          reorder: false
          filter:
            - domain:
                - input_number

    left_press_action:
      name: Left button press action
      default: []
      selector:
        action: {}

    right_press_action:
      name: Right button press action
      default: []
      selector:
        action: {}

    force_brightness:
      name: Force brightness on ON
      selector:
        boolean: {}
      default: false

    brightness_pct:
      name: Forced brightness (%)
      selector:
        number:
          min: 0
          max: 100
          step: 1
          mode: slider
      default: 50

    repeat_delay:
      name: Dim repeat delay (ms)
      selector:
        number:
          min: 0
          max: 1000
          step: 1
          mode: slider
      default: 150

    repeat_count:
      name: Dim repeat iterations
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider
      default: 20

    brightness_step_pct:
      name: Instant dimming step (%)
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider
      default: 20

    smooth_dimming:
      name: Enable smooth dimming
      selector:
        boolean: {}
      default: true

    smooth_dimming_targets:
      name: Entities using smooth dimming (optional)
      description: If empty, applies to all light targets.
      selector:
        entity:
          multiple: true
          reorder: false
          filter:
            - domain:
                - light
      default: []

    smooth_step_pct:
      name: Smooth dimming step (%)
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider
      default: 5

    dimming_transition:
      name: Smooth dimming transition (seconds)
      selector:
        number:
          min: 0
          max: 2
          step: 0.1
      default: 0.5

    prevent_turn_off_when_dimming:
      name: Prevent turning off when dimming down
      selector:
        boolean: {}
      default: true

    dimming_off_threshold_pct:
      name: Minimum brightness (%) when preventing turn off
      selector:
        number:
          min: 0
          max: 100
          step: 1
          mode: slider
      default: 1

mode: restart

trigger:
  - id: "on"
    platform: device
    device_id: !input switch_remote
    domain: mqtt
    type: action
    subtype: "on"

  - id: "off"
    platform: device
    device_id: !input switch_remote
    domain: mqtt
    type: action
    subtype: "off"

  - id: "brightness_move_up"
    platform: device
    device_id: !input switch_remote
    domain: mqtt
    type: action
    subtype: "brightness_move_up"

  - id: "brightness_move_down"
    platform: device
    device_id: !input switch_remote
    domain: mqtt
    type: action
    subtype: "brightness_move_down"

  - id: "brightness_stop"
    platform: device
    device_id: !input switch_remote
    domain: mqtt
    type: action
    subtype: "brightness_stop"

  - id: "arrow_left_click"
    platform: device
    device_id: !input switch_remote
    domain: mqtt
    type: action
    subtype: "arrow_left_click"

  - id: "arrow_right_click"
    platform: device
    device_id: !input switch_remote
    domain: mqtt
    type: action
    subtype: "arrow_right_click"

action:
  - variables:
      targets: !input targets
      selected_target: !input selected_target

      force_brightness: !input force_brightness
      brightness_pct: !input brightness_pct

      smooth_dimming: !input smooth_dimming
      smooth_targets: !input smooth_dimming_targets
      smooth_step_pct: !input smooth_step_pct
      dimming_transition: !input dimming_transition

      prevent_off: !input prevent_turn_off_when_dimming
      off_threshold_pct: !input dimming_off_threshold_pct

      target_index: >-
        {% set tlist = targets | list %}
        {% set count = tlist | count | int %}
        {% set cur = states(selected_target) | int(0) %}
        {% if count == 0 %}0
        {% elif cur < 0 %}0
        {% elif cur >= count %}{{ count - 1 }}
        {% else %}{{ cur }}
        {% endif %}

      target_entity_id: "{{ (targets | list)[target_index] }}"
      target_domain: "{{ target_entity_id.split('.')[0] }}"

      smooth_enabled: >-
        {{ smooth_dimming and ( (smooth_targets | list | count) == 0 or target_entity_id in (smooth_targets | list) ) }}

  - choose:

      # ON
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'on' }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ target_domain == 'light' and force_brightness }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ target_entity_id }}"
                    data:
                      brightness_pct: "{{ brightness_pct }}"
            default:
              - service: "{{ target_domain }}.turn_on"
                target:
                  entity_id: "{{ target_entity_id }}"

      # OFF
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'off' }}"
        sequence:
          - service: "{{ target_domain }}.turn_off"
            target:
              entity_id: "{{ target_entity_id }}"

      # DIM UP (hold)
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'brightness_move_up' and target_domain == 'light' }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ smooth_enabled }}"
                sequence:
                  - repeat:
                      count: !input repeat_count
                      sequence:
                        - variables:
                            cur_brightness: >-
                              {{ (state_attr(target_entity_id, 'brightness') | int(0) * 100 / 255) | round(0) }}
                            new_brightness: >-
                              {{ [ (cur_brightness | int) + (smooth_step_pct | int), 100 ] | min }}
                        - service: light.turn_on
                          target:
                            entity_id: "{{ target_entity_id }}"
                          data:
                            brightness_pct: "{{ new_brightness }}"
                            transition: "{{ dimming_transition }}"
                        - delay:
                            milliseconds: !input repeat_delay
            default:
              - repeat:
                  count: !input repeat_count
                  sequence:
                    - service: light.turn_on
                      target:
                        entity_id: "{{ target_entity_id }}"
                      data:
                        brightness_step_pct: !input brightness_step_pct
                    - delay:
                        milliseconds: !input repeat_delay

      # DIM DOWN (hold)
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'brightness_move_down' and target_domain == 'light' }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ smooth_enabled }}"
                sequence:
                  - repeat:
                      count: !input repeat_count
                      sequence:
                        - variables:
                            cur_brightness: >-
                              {{ (state_attr(target_entity_id, 'brightness') | int(0) * 100 / 255) | round(0) }}
                            off_threshold: >-
                              {% if prevent_off %}{{ off_threshold_pct | int }}{% else %}0{% endif %}
                            new_brightness: >-
                              {{ [ (cur_brightness | int) - (smooth_step_pct | int), off_threshold ] | max }}
                        - service: light.turn_on
                          target:
                            entity_id: "{{ target_entity_id }}"
                          data:
                            brightness_pct: "{{ new_brightness }}"
                            transition: "{{ dimming_transition }}"
                        - delay:
                            milliseconds: !input repeat_delay
            default:
              - repeat:
                  count: !input repeat_count
                  sequence:
                    - variables:
                        cur_brightness: >-
                          {{ (state_attr(target_entity_id, 'brightness') | int(0) * 100 / 255) | round(0) }}
                        off_threshold: >-
                          {% if prevent_off %}{{ off_threshold_pct | int }}{% else %}0{% endif %}
                        new_brightness: >-
                          {{ [ (cur_brightness | int) - ((states('input_number.dummy') | int(0)) + (0)) , off_threshold ] | max }}
                    - service: light.turn_on
                      target:
                        entity_id: "{{ target_entity_id }}"
                      data:
                        brightness_step_pct: -!input brightness_step_pct
                    - delay:
                        milliseconds: !input repeat_delay

      # STOP (release) - no action
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'brightness_stop' }}"
        sequence: []

      # LEFT CLICK = custom action
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'arrow_left_click' }}"
        sequence: !input left_press_action

      # RIGHT CLICK = custom action
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'arrow_right_click' }}"
        sequence: !input right_press_action
